'\" t
.TH "" 3 "" "Version Unknown To Mankind" "Free Widget Foundation"
.SH NAME
Calib
.SH DESCRIPTION

.SS "Public variables"

.ps -2
.TS
center box;
cBsss
lB|lB|lB|lB
l|l|l|l.
Calib
Name	Class	Type	Default
XtNforeground	XtCForeground	Pixel 	"White"
XtNhighlight	XtCHighlight	Pixel 	"Green"
XtNlineWidth	XtCLineWidth	int 	1 
XtNlineSize	XtCLineSize	int 	25 
XtNxpos	XtCXPos	int 	0 
XtNypos	XtCYpos	int 	0 
XtNcrossw	XtCCrossw	int 	0 
XtNcallback	XtCCallback	Callback	NULL 

.TE
.ps +2


.TP
.I "XtNforeground"



.TP
.I "XtNhighlight"



.TP
.I "XtNlineWidth"



.TP
.I "XtNlineSize"



.TP
.I "XtNxpos"



.TP
.I "XtNypos"



.TP
.I "XtNcrossw"



.TP
.I "XtNcallback"



.ps -2
.TS
center box;
cBsss
lB|lB|lB|lB
l|l|l|l.
Core
Name	Class	Type	Default
XtNx	XtCX	Position 	0 
XtNy	XtCY	Position 	0 
XtNwidth	XtCWidth	Dimension 	0 
XtNheight	XtCHeight	Dimension 	0 
borderWidth	XtCBorderWidth	Dimension 	0 
XtNcolormap	XtCColormap	Colormap 	NULL 
XtNdepth	XtCDepth	Int 	0 
destroyCallback	XtCDestroyCallback	XTCallbackList 	NULL 
XtNsensitive	XtCSensitive	Boolean 	True 
XtNtm	XtCTm	XTTMRec 	NULL 
ancestorSensitive	XtCAncestorSensitive	Boolean 	False 
accelerators	XtCAccelerators	XTTranslations 	NULL 
borderColor	XtCBorderColor	Pixel 	0 
borderPixmap	XtCBorderPixmap	Pixmap 	NULL 
background	XtCBackground	Pixel 	0 
backgroundPixmap	XtCBackgroundPixmap	Pixmap 	NULL 
mappedWhenManaged	XtCMappedWhenManaged	Boolean 	True 
XtNscreen	XtCScreen	Screen *	NULL 

.TE
.ps +2

.SS "Exports"

  x0,y0 : screen coordinate (real)
    x1,y1 : touch coordinate  (to be transformed)




.nf

.B type
 cal_point = struct { int x0,y0,x1,y1; }
.fi


.SS "Translations"


.nf
<BtnDown>: notify() 
.fi


.SS "Actions"


.TP
.I "notify



