/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_CALIBP_H
#define XTCW_CALIBP_H
#include <X11/CoreP.h>
#include <xtcw/Calib.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} CalibClassPart;

typedef struct _CalibClassRec {
CoreClassPart core_class;
CalibClassPart calib_class;
} CalibClassRec;

typedef struct {
/* resources */
Pixel  foreground;
Pixel  highlight;
int  lineWidth;
int  lineSize;
int  xpos;
int  ypos;
int  crossw;
XtCallbackList  callback;
/* private state */
GC  gc[2];
cal_point  coord[4];
int  cur_point;
} CalibPart;

typedef struct _CalibRec {
CorePart core;
CalibPart calib;
} CalibRec;

externalref CalibClassRec calibClassRec;

_XFUNCPROTOEND
#endif /* XTCW_CALIBP_H */
