/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_CALIB_H
#define XTCW_CALIB_H
#include <X11/Core.h>
_XFUNCPROTOBEGIN
typedef struct { int x0,y0,x1,y1; } cal_point;

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNhighlight
#define XtNhighlight "highlight"
#endif
#ifndef XtCHighlight
#define XtCHighlight "Highlight"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNlineWidth
#define XtNlineWidth "lineWidth"
#endif
#ifndef XtCLineWidth
#define XtCLineWidth "LineWidth"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNlineSize
#define XtNlineSize "lineSize"
#endif
#ifndef XtCLineSize
#define XtCLineSize "LineSize"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNxpos
#define XtNxpos "xpos"
#endif
#ifndef XtCXPos
#define XtCXPos "XPos"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNypos
#define XtNypos "ypos"
#endif
#ifndef XtCYpos
#define XtCYpos "Ypos"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcrossw
#define XtNcrossw "crossw"
#endif
#ifndef XtCCrossw
#define XtCCrossw "Crossw"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcallback
#define XtNcallback "callback"
#endif
#ifndef XtCCallback
#define XtCCallback "Callback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _CalibClassRec *CalibWidgetClass;
typedef struct _CalibRec *CalibWidget;
externalref WidgetClass calibWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_CALIB_H */
