/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 148 "Calib.widget"
#include <stdio.h>
#include <xtcw/CalibP.h>
#line 116 "Calib.widget"
static void notify(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"notify", notify},
};

static char defaultTranslations[] = "\
<BtnDown>: notify() \n\
";
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 26 "Calib.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 32 "Calib.widget"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 54 "Calib.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 60 "Calib.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 67 "Calib.widget"
static void alloc_colors(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 84 "Calib.widget"
static void x_draw_cross(
#if NeedFunctionPrototypes
Widget,int ,int ,int ,int 
#endif
);
#line 92 "Calib.widget"
static void draw_cross(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 104 "Calib.widget"
static void redraw(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 67 "Calib.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 67 "Calib.widget"
static void alloc_colors(Widget self)
#else
#line 67 "Calib.widget"
static void alloc_colors(self)Widget self;
#endif
#line 68 "Calib.widget"
{
    if( ((CalibWidget)self)->calib.gc[0] ) XtReleaseGC(self, ((CalibWidget)self)->calib.gc[0] );
    if( ((CalibWidget)self)->calib.gc[1] ) XtReleaseGC(self, ((CalibWidget)self)->calib.gc[1] );

    XtGCMask mask;
    XGCValues values;
    mask = GCForeground | GCLineWidth | GCLineStyle | GCGraphicsExposures;
    values.foreground = ((CalibWidget)self)->calib.foreground;
    values.line_width = ((CalibWidget)self)->calib.lineWidth;
    values.line_style = LineSolid;
    values.graphics_exposures = False;
    ((CalibWidget)self)->calib.gc[0] = XtGetGC(self,mask,&values);
    values.foreground = ((CalibWidget)self)->calib.highlight;
    ((CalibWidget)self)->calib.gc[1] = XtGetGC(self,mask,&values);
}
#line 84 "Calib.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 84 "Calib.widget"
static void x_draw_cross(Widget self,int  x,int  y,int  w,int  c)
#else
#line 84 "Calib.widget"
static void x_draw_cross(self,x,y,w,c)Widget self;int  x;int  y;int  w;int  c;
#endif
#line 85 "Calib.widget"
{
         XDrawLine( XtDisplay(self), XtWindow(self), ((CalibWidget)self)->calib.gc[c],
                   x - w, y, x +w, y );
         XDrawLine( XtDisplay(self), XtWindow(self), ((CalibWidget)self)->calib.gc[c],
                   x, y-w, x, y+w );
}
#line 92 "Calib.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 92 "Calib.widget"
static void draw_cross(Widget self,int  num,int  c)
#else
#line 92 "Calib.widget"
static void draw_cross(self,num,c)Widget self;int  num;int  c;
#endif
#line 93 "Calib.widget"
{
        if( num > 3) num = 3;
        int x,y;
        x= ((CalibWidget)self)->calib.xpos; y = ((CalibWidget)self)->calib.ypos;
        if( num == 1 || num == 2 ) x = ((CalibWidget)self)->core.width - x;
        if( num == 2 || num == 3 ) y = ((CalibWidget)self)->core.height - y;
        x_draw_cross( self, x,y,((CalibWidget)self)->calib.crossw, c != 0 );
        ((CalibWidget)self)->calib.coord[num].x0 = x;
        ((CalibWidget)self)->calib.coord[num].y0 = y;
}
#line 104 "Calib.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 104 "Calib.widget"
static void redraw(Widget self)
#else
#line 104 "Calib.widget"
static void redraw(self)Widget self;
#endif
#line 105 "Calib.widget"
{
        int i;
        for( i=0; i<= ((CalibWidget)self)->calib.cur_point; i++ )
             draw_cross(self,i, i == ((CalibWidget)self)->calib.cur_point );
}

static XtResource resources[] = {
#line 11 "Calib.widget"
{XtNforeground,XtCForeground,XtRPixel,sizeof(((CalibRec*)NULL)->calib.foreground),XtOffsetOf(CalibRec,calib.foreground),XtRString,(XtPointer)"White"},
#line 12 "Calib.widget"
{XtNhighlight,XtCHighlight,XtRPixel,sizeof(((CalibRec*)NULL)->calib.highlight),XtOffsetOf(CalibRec,calib.highlight),XtRString,(XtPointer)"Green"},
#line 13 "Calib.widget"
{XtNlineWidth,XtCLineWidth,XtRInt,sizeof(((CalibRec*)NULL)->calib.lineWidth),XtOffsetOf(CalibRec,calib.lineWidth),XtRImmediate,(XtPointer)1 },
#line 14 "Calib.widget"
{XtNlineSize,XtCLineSize,XtRInt,sizeof(((CalibRec*)NULL)->calib.lineSize),XtOffsetOf(CalibRec,calib.lineSize),XtRImmediate,(XtPointer)25 },
#line 15 "Calib.widget"
{XtNxpos,XtCXPos,XtRInt,sizeof(((CalibRec*)NULL)->calib.xpos),XtOffsetOf(CalibRec,calib.xpos),XtRImmediate,(XtPointer)0 },
#line 16 "Calib.widget"
{XtNypos,XtCYpos,XtRInt,sizeof(((CalibRec*)NULL)->calib.ypos),XtOffsetOf(CalibRec,calib.ypos),XtRImmediate,(XtPointer)0 },
#line 17 "Calib.widget"
{XtNcrossw,XtCCrossw,XtRInt,sizeof(((CalibRec*)NULL)->calib.crossw),XtOffsetOf(CalibRec,calib.crossw),XtRImmediate,(XtPointer)0 },
#line 18 "Calib.widget"
{XtNcallback,XtCCallback,XtRCallback,sizeof(((CalibRec*)NULL)->calib.callback),XtOffsetOf(CalibRec,calib.callback),XtRImmediate,(XtPointer)NULL },
};

CalibClassRec calibClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &coreClassRec,
/* class_name   	*/  "Calib",
/* widget_size  	*/  sizeof(CalibRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  actionsList,
/* num_actions  	*/  1,
/* resources    	*/  resources,
/* num_resources 	*/  8,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  NULL,
/* resize       	*/  resize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  defaultTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Calib_class part */
 /* dummy */  0
},
};
WidgetClass calibWidgetClass = (WidgetClass) &calibClassRec;
/*ARGSUSED*/
#line 116 "Calib.widget"
static void notify(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
        Display *disp = XtDisplay(self);
        int num = ((CalibWidget)self)->calib.cur_point;
        if( num > 3 ) num = 3;
        Window child_return;
        int x,y;
        int x0 = event->xbutton.x;
        int y0 = event->xbutton.y;

        XTranslateCoordinates (disp, XtWindow(self), DefaultRootWindow(disp),
                              x0, y0, & x, & y, & child_return);
        ((CalibWidget)self)->calib.coord[num].x1 = x;
        ((CalibWidget)self)->calib.coord[num].y1 = y;

        x0 = ((CalibWidget)self)->calib.coord[num].x0;
        y0 = ((CalibWidget)self)->calib.coord[num].y0;
        XTranslateCoordinates (disp, XtWindow(self), DefaultRootWindow(disp),
                              x0, y0, & x, & y, & child_return);
        ((CalibWidget)self)->calib.coord[num].x0 = x;
        ((CalibWidget)self)->calib.coord[num].y0 = y;

        if( num == 3 ) {
            num=0;
            XClearWindow( XtDisplay(self), XtWindow(self) );
            XtCallCallbackList( self, ((CalibWidget)self)->calib.callback, ((CalibWidget)self)->calib.coord );
        } else num++;
        ((CalibWidget)self)->calib.cur_point = num;
        ((CalibWidgetClass)self->core.widget_class)->core_class.expose(self,NULL,0);
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  CalibWidgetClass c __attribute__((unused)) = (CalibWidgetClass) class;
  CalibWidgetClass super __attribute__((unused));
  if (class == calibWidgetClass) return;
  super = (CalibWidgetClass)class->core_class.superclass;
}
#line 26 "Calib.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 26 "Calib.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 26 "Calib.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 27 "Calib.widget"
{
        ((CalibWidget)self)->core.width=10; ((CalibWidget)self)->core.height=10;
        alloc_colors(self);
}
#line 32 "Calib.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 32 "Calib.widget"
static void resize(Widget self)
#else
#line 32 "Calib.widget"
static void resize(self)Widget self;
#endif
#line 33 "Calib.widget"
{
        if( ((CalibWidget)self)->calib.lineSize < 1 ) ((CalibWidget)self)->calib.lineSize = 1;
        float h = ((CalibWidget)self)->calib.lineSize * 1.0 / 100.0;
        int xoff = ((CalibWidget)self)->core.width * 1.0 * h;
        int yoff = ((CalibWidget)self)->core.height * 1.0 * h;
        int w;
        if( xoff / 2 < yoff / 2 ) w = xoff/2; else w=yoff/2;

        xoff = w * 1.5;
        yoff = w * 1.5;

        if( xoff < 2 ) xoff=2;
        if( yoff < 2 ) yoff=2;
        if( w    < 2 ) w = 2;

        ((CalibWidget)self)->calib.xpos = xoff;
        ((CalibWidget)self)->calib.ypos = yoff;
        ((CalibWidget)self)->calib.crossw = w;
        ((CalibWidget)self)->calib.cur_point = 0;
}
#line 54 "Calib.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 54 "Calib.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 54 "Calib.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 55 "Calib.widget"
{
        XClearWindow( XtDisplay(self), XtWindow(self) );
        redraw(self);
}
#line 60 "Calib.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 60 "Calib.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 60 "Calib.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 61 "Calib.widget"
{
        alloc_colors(self);
        return True;
}
#line 8 "Calib.widget"
